Traceback (most recent call last):
  File "main.py", line 17, in <module>
    state = sys.argv[1]
IndexError: list index out of range
